export const environment = {
  production: true,
  clientId: "ADMINWEB",
  TALENT_DEFAULT_IMG: "assets/img/profile/talent_default_img.png",
  PROFESSIONAL_DEFAULT_IMG: "assets/img/profile/professional_default_img.png",
  NO_MEDIA_IMG: "assets/img/no-media.png",
  COMMENTER_DEFAULT_IMAGE: "assets/img/contest/popup-user.png",
  BASE_URL: "https://www.untappedpool.ng/v1",
  IMAGE_BUCKET: "untapped-pool-image-production",
  CLOUD_FORMATION_API: "https://d2t7flob0izurn.cloudfront.net",
  S3BUCKET_OBJECT_URL:
    "https://untapped-pool-image-production.s3.eu-west-3.amazonaws.com",
  ART_ALBUM_COVER: "assets/img/profile/audio-cover.jpg",
  VIDEO_ALBUM_COVER: "assets/img/profile/video-cover.jpg",
  AUDIO_ACCELERATE_URL:
    "https://untapped-pool-audio-production.s3.eu-west-3.amazonaws.com",
  VIDEO_ACCELERATE_URL:
    "https://untapped-pool-video-production.s3.eu-west-3.amazonaws.com",
  PROFESSIONAL_BANNER_IMAGE_DEFAULT: "assets/img/profile/profile-3.jpg",
  PROFESSIONAL_BIODATA_BANNER_DEFAULT:
    "assets/img/profile/pro_banner_default.png",
  CONTEST_BANNER_DEFAULT: "assets/img/contest/contest-1.jpg",
  PAYSTACK_CLIENT_KEY: "pk_live_bd4b94fbc002f8922e69c4ead360087cc6487f1e",
  EMAIL_CHANGE_ROUTE: "account/email-change/verify",
  RESET_PASSWORD_URL: "account/reset/password-request/verify",
  CONTEST_KEYWORD: "TALENT",
  CONTEST_TO_NUMBER: "32811",
  WS_ENDPOINT: "http://127.0.0.1:8900",
  PUSHER_KEY: "4ca9155811a0dd70c020",
  PUSHER_CLUSTER: "eu",
  PUSHER_CHANNEL: "untapped-pool-production",
  TERMS_CONDITION_LAST_DATE: "June 17, 2020",
  KEY: "311A35EAE8CEDB052F1E8533FE3DBC12",
  TALENT_USER_TYPE_ID: "5dcb700d625f0d6058704ef0",
  PROFESSIONAL_USER_TYPE_ID: "5dcb6ff6625f0d6058704eef",
  COMPETITION_TERMS_LAST_DATE: "July 13, 2020",
  PRIVACY_POLICY_LAST_DATE: "June 18, 2020",
};
