export const UPLOAD_ACTION = {
    UPLOAD_PROFILE_IMAGE: 'UPLOAD_PROFILE_IMAGE',
    UPLOAD_PORTFOLIO: 'UPLOAD_PORTFOLIO',
    UPLOAD_GIG: 'UPLOAD_GIG'
};

export const SOCIAL_MEDIAS = {
    TWITTER: 'TWITTER',
    FACEBOOK: 'FACEBOOK',
    INSTAGRAM: 'INSTAGRAM',
    YOUTUBE: 'YOUTUBE'
};
